# options for analysis running
run:

  timeout: 5m
  skip-dirs-use-default: false
  skip-dirs:
    - pkg/helm

  modules-download-mode: readonly
  allow-parallel-runners: true

linters:
  enable:
    - golint
    - gofmt

linters-settings:
  gofmt:
    # simplify code: gofmt with `-s` option, true by default
    simplify: false
  golint:
    min-confidence: 0