name: "Close stale PRs"
on:
  schedule:
    - cron: "0 23 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GH_TOKEN }}
          # Empty message to prevent issues from being closed or staled
          stale-issue-message: ''
          stale-pr-message: 'The PR is marked as stale since no activity has been recorded in 30 days'
          days-before-stale: 30
          close-pr-label: "stale"
